config = {
    # Block graph: edit a stage implementation independently without touching CLI dispatch.
    "pipeline": {
        "cache-proposals": {"type": "CacheProposalsBlock"},
        "search": {"type": "SearchBlock"},
        "evaluate": {"type": "EvaluateBlock"},
        "export": {"type": "ExportBlock"},
    },
    "dataset": {
        "type": "Img2GPS3KDataset",
        "root": "datasets/img2gps3k",
        "csv": "test_set/im2gps3k_places365.csv",
        "images": "test_set/im2gps3ktest/im2gps3ktest",
        "expected_count": 2997,
        "discovery_count": 1079,
    },
    "proposer": {
        "type": "WeDetectUniONNX",
        "model_path": "models/wedetect_uni_base.onnx",
        "input_size": 640,
        "score_threshold": 0.15,
        "nms_threshold": 0.7,
    },
    "geoclip": {
        "type": "GeoCLIPLocalizer",
        "weights_path": "geo-clip/geoclip/model/weights",
        "gallery_path": "geo-clip/geoclip/model/gps_gallery/coordinates_100K.csv",
        "gallery_cache": "gallery_embeddings.pt",
        "processor_model": "openai/clip-vit-large-patch14",
        "expected_gallery_count": 100000,
    },
    "runtime": {
        "device": "cuda",
        "output_dir": "outputs/geoprobe",
        "seed": 42,
        "deterministic": True,
        "dtype": "float32",
    },
    # Intervention blocks are intentionally explicit. Change mask geometry, one vision
    # layer, or search scheduling here without modifying inference orchestration.
    "intervention": {
        "mask": {
            "score_threshold": 0.4,
            "max_proposals": 100,
            "crop_size": 224,
            "patch_grid": 16,
        },
        "vision": {
            "expected_heads": 16,
            "layers": [
                {"index": 0, "name": "vision-block-00", "search_order": None},
                {"index": 1, "name": "vision-block-01", "search_order": None},
                {"index": 2, "name": "vision-block-02", "search_order": 0},
                {"index": 3, "name": "vision-block-03", "search_order": 4},
                {"index": 4, "name": "vision-block-04", "search_order": 1},
                {"index": 5, "name": "vision-block-05", "search_order": None},
                {"index": 6, "name": "vision-block-06", "search_order": None},
                {"index": 7, "name": "vision-block-07", "search_order": 2},
                {"index": 8, "name": "vision-block-08", "search_order": None},
                {"index": 9, "name": "vision-block-09", "search_order": None},
                {"index": 10, "name": "vision-block-10", "search_order": None},
                {"index": 11, "name": "vision-block-11", "search_order": None},
                {"index": 12, "name": "vision-block-12", "search_order": 3},
                {"index": 13, "name": "vision-block-13", "search_order": None},
                {"index": 14, "name": "vision-block-14", "search_order": None},
                {"index": 15, "name": "vision-block-15", "search_order": None},
                {"index": 16, "name": "vision-block-16", "search_order": None},
                {"index": 17, "name": "vision-block-17", "search_order": None},
                {"index": 18, "name": "vision-block-18", "search_order": None},
                {"index": 19, "name": "vision-block-19", "search_order": None},
                {"index": 20, "name": "vision-block-20", "search_order": None},
                {"index": 21, "name": "vision-block-21", "search_order": None},
                {"index": 22, "name": "vision-block-22", "search_order": None},
                {"index": 23, "name": "vision-block-23", "search_order": None},
            ],
        },
        "search": {
            "schedules": ["fixed", "sqrt", "linear"],
            "base_bias": 2.0,
        },
    },
    "metrics": {
        "thresholds_km": [1, 25, 200, 750, 2500],
        "clip_improvement_km": 2500.0,
        "earth_radius_km": 6371.0088,
        "bootstrap_resamples": 10000,
        "bootstrap_confidence": 0.95,
    },
}
